export const actions = {
  profile: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_DATA_FETCHED",
    DATA_FETCHED_FAVOURITE: "PROFILE_FAVOURITE_DATA_FETCHED",
    DATA_FETCH_ERROR: "PROFILE_DATA_FETCHED_ERROR",
  },
  blog: {
    DATA_FETCHING: "BLOG_DATA_FETCHING",
    DATA_FETCHED: "BLOG_DATA_FETCHED",
    DATA_POPULAR_FETCHED: "BLOG_POPULAR_DATA_FETCHED",
    DATA_SINGLE_FETCHED: "BLOG_SINGLE_DATA_FETCHED",
    DATA_FETCH_ERROR: "BLOG_DATA_FETCH_ERROR",
    BLOG_CREATED: "BLOG_DATA_CREATED",
    BLOG_EDITED: "BLOG_DATA_EDITED",
    BLOG_DELETED: "BLOG_DATA_DELETED",
    BLOG_LIKED: "BLOG_DATA_LIKED",
    BLOG_COMMENTED: "BLOG_DATA_COMMENTED",
  },
};
